---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  namespace: development
spec:
  memberOf: [platform]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
  namespace: development
spec:
  type: team
  children: []
